
services:

  selenoid:
    image: "aerokube/selenoid:latest"
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - selenoid
    volumes:
      - "./:/etc/selenoid:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./target:/opt/selenoid/video"
    environment:
      - "DOCKER_API_VERSION=1.40"
      - "OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/target"
    command:
      [
        "-conf",
        "/etc/selenoid/browsers.json",
        "-video-output-dir",
        "/opt/selenoid/video",
        "-container-network",
        "selenoid"
      ]

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    container_name: selenoid-ui
    depends_on:
      - selenoid
    ports:
      - "8080:8080"
    networks:
      - selenoid
    command:
      [
        "--selenoid-uri",
        "http://selenoid:4444"
      ]

networks:
  selenoid:
    name: selenoid
